### ISSUE TITLE
New colour palettes do not match scatr marginals

### ISSUE THREAD

**Issue by HRDudeness** [raviselker/scatr#2]
With the addition of colour palettes in jamovi 0.9.19 the colours of the optional marginal densities or boxplots do not match the data points and regression lines in the scatterplot anymore. The palette "Set1" comes closest to the original, but still does not really match.

<img width="719" alt="scatr-colors" src="https://user-images.githubusercontent.com/27767378/43190821-38823aaa-8ffa-11e8-9a7f-58a5a308133c.png">

**Comment by raviselker** [comment]
Oh yeah, forgot about that. I'll update scatr asap. Thanks for reporting!

**Comment by raviselker** [comment]
The new version (available in the jamovi library) fixes this

**Comment by HRDudeness** [comment]
Thanks! Just updated it and everything seems fine :-)
